### ISSUE TITLE
Trade Terminal Sales

### ISSUE THREAD

**Issue by flipcyde** [BIG-Games-LLC/ps99-public-api-docs#28] opened 2024-03-30 01:00 UTC
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

It would be awesome to get access to the near-real time terminal sales

**Comment by chickenputty** [comment] 2024-10-12 01:03
Duplicate of https://github.com/BIG-Games-LLC/ps99-public-api-docs/issues/14

**Closed by chickenputty** 2024-10-12 01:03 UTC
Labels: feature
